name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        sudo apt install cmake
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake ../
        cmake --build .
    - name: run-tests
      run: |
        ./tests
    
